#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint ||
(
  echo "\n ❌ - yarn lint Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Code successfully linted, now applying default formatting to the code.. \n"
  true;
) &&

yarn format ||
(
  echo "\n ❌ - yarn format Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Code successfully formatted, adding formatted files to git..\n"
  true;
) &&

git add . ||
(
  echo "\n ❌ - git add Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Formatted files successfully added to git, now compiling Typescript..\n"
  true;
) &&

npx tsc ||
(
  echo "\n ❌ - npx tsc Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Typescript successfully compiled. I am now committing this! - 🚀🔥\n"
  true;
) 
